doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      openconext_user_lifecycle:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/OpenConext/UserLifecycle/Domain/Entity"
        prefix: OpenConext\UserLifecycle\Domain\Entity
        alias: OpenConextUserLifecycle
