doctrine:
    dbal:
        dbname: '%database_name%'
        host: '%database_host%'
        port: '%database_port%'
        user: '%database_user%'
        password: '%database_password%'
        driver: pdo_mysql
        charset: UTF8

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            openconext_user_lifecycle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/OpenConext/UserLifecycle/Domain/Entity'
                prefix: 'OpenConext\UserLifecycle\Domain\Entity'
                alias: OpenConextUserLifecycle
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            driver: pdo_sqlite
            path: "%kernel.project_dir%/var/user-lifecycle.sqlite"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
