monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler: syslog
            channels: ['!event', '!doctrine']
        syslog:
            type: syslog
            ident: userlifecycle_stats
            formatter: OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Monolog\Formatter\JsonFormatter
