security:
    providers:
        users_in_memory:
            memory:
                users:
                    "%deprovision_api_settings_username%":
                        password: "%deprovision_api_settings_password%"
                        roles: 'ROLE_ADMIN'
    password_hashers:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        monitor:
            pattern: ^/(internal/)?(info|health)$
            security: false
        main:
            http_basic: ~

    access_control:
        - { path: ^/api/deprovision, roles: ROLE_ADMIN }


