language: php

php:
  - 5.6
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - phpenv config-add travis.php.ini
  - composer install --no-interaction

script:
  - ant

branches:
  only:
    - develop
    - master