---

version: "3.8"

services:
  php-fpm:
    image: ghcr.io/openconext/openconext-containers/openconext-phpfpm-dev:latest
    volumes:
      - .:/var/www/html/
      - type: bind
        source: /dev/log
        target: /dev/log
    environment:
      - PHPFPM_PORT=9000
    networks:
      userlifecycle:
        aliases:
          - userlifecycle_php-fpm

networks:
  userlifecycle:
