imports:
    - { resource: config_dev.yml }
    - { resource: '../../tests/integration/UserLifecycleBundle/Resources/config/services.yml' }
    - { resource: parameters.test.yml }

doctrine:
    dbal:
        driver: pdo_sqlite
        path: "/tmp/user-lifecycle-test.sqlite"

framework:
    test: ~