imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%kernel.root_dir%/../var/user-lifecycle.sqlite"

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
