monolog:
    handlers:
        main:
            type: syslog
            ident: userlifecycle
            facility: user
            channels: ['!event', '!doctrine']
            level: INFO
            formatter: OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Monolog\Formatter\JsonFormatter
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: CRITICAL
            channels: ['!event', '!doctrine']
