# This file# This DI configuration file contains overrides on the DashboardBundle configuration,
# typically to replace doctrine repositories with in-memory repositories.
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: user-lifecycle
    database_user: user-lifecycle
    database_password: secret
    secret: g6lfd320932jfasdlkj320912u3jwfelsfd
    open_conext_user_lifecycle_clients:
        my_service_name:
            url: 'https://my-service-url/api/'
            username: my-user-name
            password: secret
            verify_ssl: false
        my_second_name:
            url: 'https://my-second-service-url/api/'
            username: my-user-name
            password: secret
    user_quota: 1500
    inactivity_period: 37
