controllers:
    resource:
        path: ../src/OpenConext/UserLifecycle/Infrastructure/UserLifecycleBundle/Controller/
        namespace: OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Controller
    type: attribute

open_conext_monitor:
    resource: "@OpenConextMonitorBundle/src/Controller"
    type: attribute
    prefix: /

