# Install the "REMI" repo which contain newer php packages that override the default
# that come with the distro (CentOS7: 5.4; CentOS6: 5.3)
- name: Install REMI repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable REMI repo
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo

- name: Install common packages
  yum: name={{item}} state=present
  with_items:
  - yum-utils
  - vim
  - composer
  - git

- name: enable remi-php72
  shell: yum-config-manager --enable remi-php72

- name: Install php-(cli,fpm, ..)
  yum: name={{item}} state=present
  with_items:
  - php-fpm
  - php-cli
  - php-mbstring
  - php-mcrypt
  - php-intl
  - php-dom
  - php-xdebug
  - php-pecl-memcache
  - php-pdo

- name: php-fpm config
  template:
    src: '{{ item }}.j2'
    dest: /etc/php-fpm.d/{{ item }}
  with_items:
     - php-fpm-pool.conf
  notify:
    - restart php-fpm

- name: Put php.ini
  template: src='php.ini.j2' dest='/etc/php.ini'
  notify:
    - restart php-fpm

- name: Put default xdebug config
  template: src='files/xdebug.ini' dest='/etc/php.d/xdebug.ini'
  notify:
    - restart php-fpm

# Remove default conf files
- name: Remove known default distro files in /etc/nginxconf.d/ and /etc/php-fpm.d/
  file: path={{item}} state=absent
  with_items:
  - /etc/php-fpm.d/www.conf
  notify:
  - restart php-fpm

# Install php and nginx conf files
- name: Put /etc/php-fpm.conf
  copy: src='files/php-fpm.conf' dest='/etc/php-fpm.conf'
  notify:
      - restart php-fpm

- name: Start and enable php-fpm
  service: name={{item}} state=started enabled=true
  with_items:
  - php-fpm
