#!/usr/bin/env sh

cd $(dirname $0)/../../

# https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage
./vendor/bin/phpcs --report=full --standard=ci/qa/phpcs.xml --warning-severity=0 --extensions=php src
./vendor/bin/phpcs --report=full --standard=ci/qa/phpcs_tests.xml --warning-severity=0 --extensions=php tests
