services:

    OpenConext\UserLifecycle\Application\:
        resource: '../../../../Application/'
        exclude: '../../../../Application/Query'
        autoconfigure: true
        autowire: true

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Monolog\Formatter\:
        resource: '../../Monolog/Formatter'
        autoconfigure: true
        autowire: true

    OpenConext\UserLifecycle\Application\Service\SanityCheckService:
        arguments:
            - '%user_quota%'
            - '@logger'

    OpenConext\UserLifecycle\Application\Service\LastLoginService:
        arguments:
            - '%inactivity_period%'
            - '@OpenConext\UserLifecycle\Application\QueryHandler\InactiveUsersQueryHandlerInterface'
            - '@logger'

    OpenConext\UserLifecycle\Domain\:
        resource: '../../../../Domain/'
        autoconfigure: true
        autowire: false

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Command\InformationCommand:
        arguments:
            - '@OpenConext\UserLifecycle\Application\Service\InformationService'
            - '@OpenConext\UserLifecycle\Application\Service\SummaryService'
            - '@logger'
        tags:
            - 'console.command'

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Command\DeprovisionCommand:
        arguments:
            - '@OpenConext\UserLifecycle\Application\Service\DeprovisionService'
            - '@OpenConext\UserLifecycle\Application\Service\SummaryService'
            - '@OpenConext\UserLifecycle\Application\Service\ProgressReporter'
            - '@logger'
        tags:
            - 'console.command'

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Api\DeprovisionApiFeatureToggle:
        class: OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Api\DeprovisionApiFeatureToggle

    OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Controller\ApiController:
        arguments:
            - '@OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Api\DeprovisionApiFeatureToggle'

    OpenConext\UserLifecycle\Domain\Repository\LastLoginRepositoryInterface:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - OpenConext\UserLifecycle\Domain\Entity\LastLogin

    OpenConext\UserLifecycle\Domain\Client\InformationResponseFactoryInterface: '@OpenConext\UserLifecycle\Application\Client\InformationResponseFactory'

    open_conext.user_lifecycle.deprovision_client_collection:
        class: OpenConext\UserLifecycle\Infrastructure\UserLifecycleBundle\Client\DeprovisionClientCollection

    open_conext.user_lifecycle.deprovision_client.guzzle_stack:
        public: false
        class: 'GuzzleHttp\HandlerStack'
        factory: ['GuzzleHttp\HandlerStack', create]
        calls:
            - [setHandler, ['@open_conext.user_lifecycle.deprovision_client.guzzle_handler']]

    open_conext.user_lifecycle.deprovision_client.guzzle_handler:
        public: false
        class: 'GuzzleHttp\Handler\CurlMultiHandler'